#!/bin/bash
#PBS -l mem=62gb,nodes=1:ppn=24,walltime=48:00:00
#PBS -A hirschc1
#PBS -m abe
#PBS -o /home/hirschc1/pmonnaha/OandE/Cutadapt.o
#PBS -e /home/hirschc1/pmonnaha/OandE/Cutadapt.e
#PBS -M pmonnaha@umn.edu
#PBS -q mesabi

# Load modules
module load parallel
module load cutadapt/1.8.1

# We have built the jobs already so we want to just feed them to a huge
# parallel run.
TASKS="/home/hirschc1/pmonnaha/JobScripts/Cutadapt_jobs.txt"

# Run them with a huge parallel command. this is taken from the MSI help page
# that has an example of how to do this:
# https://www.msi.umn.edu/support/faq/how-can-i-use-gnu-parallel-run-lot-commands-parallel

cat ${PBS_NODEFILE}

# Uncomment the next line for running parallel across multiple nodes
#parallel -v -v -t --jobs 24 --sshloginfile ${PBS_NODEFILE} --workdir ${PWD} < ${TASKS}
# Uncomment the next line for single-node parallel
parallel < ${TASKS}

